name: Build / Linting errors
on:
  pull_request:
  push:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - trunk
      - master
    paths-ignore:
      - '.github/**'
      - 'assets/'
      - .dockerignore
      - gradle.properties
      - '**.md'
      - LICENSE
      - renovate.json
      - settings.gradle.kts
jobs:
  ktlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [16, 17]

    steps:
      - name: Checks out the repository
        uses: actions/checkout@v2

      - name: Sets up Java v${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt # AdoptOpenJDK is <3
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-test-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-test-gradle-

      - name: Lets ./gradlew be executable
        run: chmod +x ./gradlew

      - name: Lints the repository for any code errors
        run: ./gradlew spotlessCheck

      - name: Builds the project for any errors
        run: ./gradlew compileKotlin
