name: Release job
on:
  release:
    types:
      - published
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Gradle cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-test-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-test-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check if project can be built
        run: ./gradlew compileKotlin

      - name: Run all tests
        run: ./gradlew test

      - name: Publish!
        run: ./gradlew publish -Dorg.gradle.s3.endpoint=https://s3.wasabisys.com
