name: Release job
on:
  release:
    types:
      - published
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Gradle cache
        uses: actions/cache@v3.0.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-test-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-test-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check if project can be built
        run: ./gradlew compileKotlin

      - name: Apply secrets in gradle/publishing.properties
        run: |
          echo "${{ secrets.S3_PROPS }}" >> gradle/publishing.properties

      - name: Publish!
        run: ./gradlew publish -Dorg.gradle.s3.endpoint=${{ secrets.S3_ENDPOINT }}
